name: Build Crash-utility
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  X86_64:
    runs-on: ubuntu-latest
    container: amd64/ubuntu
    steps:
      - uses: actions/checkout@v4
      - name: install deps
        run: dnf install -y git make gcc gcc-c++ glibc bc bison lzo-devel snappy-devel libzstd-devel wget texinfo flex ncurses-devel patch
      - name: echo "uname -a"
        run: uname -a

  arm64:
    runs-on: ubuntu-latest
    container: arm64v8/ubuntu
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: actions/checkout@v4
      - name: install deps
        run: dnf install -y git make gcc gcc-c++ glibc bc bison lzo-devel snappy-devel libzstd-devel wget texinfo flex ncurses-devel patch
      - name: echo "uname -a"
        run: uname -a
