name: Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch:
        - arm64
        - s390x
        - i686
        - powerpc64le
        - x86_64-x32
        include:
          - arch: x86_64
          - arch: x86_64
            libxen: libxen
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Environment
      env:
        LIBXEN: ${{ matrix.libxen }}
        ARCH: ${{ matrix.arch }}
      run: |
        case $LIBXEN in
          libxen) EXTRA_PKGS+=" libxen-dev" ;;
        esac

        case $ARCH in
          arm64)       GNU_ARCH="aarch64-linux-gnu" ;;
          x86_64)      GNU_ARCH="x86_64-linux-gnu" ;;
          x86_64-x32)  GNU_ARCH="x86_64-linux-gnux32"
                       CROSS_COMPILER_PKG="gcc-x86-64-linux-gnux32" ;;
          *)           GNU_ARCH="$ARCH-linux-gnu" ;;
        esac

        if [ -n "$GNU_ARCH" ]; then
          if [ -z "$CROSS_COMPILER_PKG" ]; then
            CROSS_COMPILER_PKG="gcc-$GNU_ARCH"
          fi
          EXTRA_PKGS+=" $CROSS_COMPILER_PKG"
          CONFIG_FLAGS+=" --host=$GNU_ARCH"
        fi

        echo "EXTRA_PKGS=$EXTRA_PKGS" >> $GITHUB_ENV
        echo "CONFIG_FLAGS=$CONFIG_FLAGS" >> $GITHUB_ENV
        echo "GNU_ARCH=$GNU_ARCH" >> $GITHUB_ENV

    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install patch gcc g++ liblzo2-dev libsnappy-dev libzstd-dev wget texinfo bison flex 

    - name: Install extra pkgs
      if: env.EXTRA_PKGS != ''
      run: |
        sudo apt-get update
        sudo apt-get -q=2 install ${{ env.EXTRA_PKGS }}

    - name: Build
      run: |
        make CROSS_COMPILE=${{ env.GNU_ARCH }}- -j"$(nproc)" warn lzo zstd snappy
