name: Build Crash-utility
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  X86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install deps
        run: sudo apt-get install patch gcc g++ liblzo2-dev libsnappy-dev libzstd-dev wget texinfo bison flex
      - name: echo "uname -a"
        run: sudo uname -a

  arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install qemu pkgs
        run: sudo apt-get install binfmt-support qemu-user-static
      - name: fetch qemu aarch64 static tarball
        run: sudo wget https://github.com/multiarch/qemu-user-static/releases/download/v7.2.0-1/qemu-aarch64-static.tar.gz
      - name: uncompress tarball
        run: sudo tar -zxvf qemu-aarch64-static.tar.gz
      - name: copy file
        run: sudo cp qemu-aarch64-static /usr/bin/
      - name: change mod
        run: sudo chmod +x /usr/bin/qemu-aarch64-static
      - name: docker run
        run: sudo docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - name: docker run 2...
        run: sudo docker run -t -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static arm64v8/ubuntu:latest
      - name: install deps
        run: sudo apt-get install patch gcc g++ liblzo2-dev libsnappy-dev libzstd-dev wget texinfo bison flex
      - name: echo "uname -a"
        run: sudo uname -a

